spring.application.name=lab-security-jwt

# esenezeta: Configuracion JWT con Fallback
security.jwt.secret-key=${SECURITY_JWT_SECRET_KEY:esta_es_una_llave_secreta_muy_larga_y_segura_para_el_laboratorio_snz_2026}
security.jwt.expiration-time=${SECURITY_JWT_EXPIRATION_TIME:3600000}

# Configuracion de Base de Datos para Docker
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/lab_security_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:esenezeta}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Esenezeta2026}

# Hibernate y JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect