spring.application.name=lab-security-jwt

# esenezeta: Asegurate de que esta llave sea privada y no se comparta
security.jwt.secret-key=esta_es_una_llave_secreta_muy_larga_y_segura_para_el_laboratorio_snz_2026
security.jwt.expiration-time=3600000